# Generated by Django 4.1.7 on 2023-12-16 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='comment',
    #         name='author',
    #         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_author', to=settings.AUTH_USER_MODEL),
    #     ),
    #     migrations.AddField(
    #         model_name='comment',
    #         name='post',
    #         field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='posts.post'),
    #         preserve_default=False,
    #     ),
    #     migrations.AddField(
    #         model_name='post',
    #         name='author',
    #         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
    #     ),
    #     migrations.AddField(
    #         model_name='post',
    #         name='likes',
    #         field=models.ManyToManyField(blank=True, null=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
    #     ),
    #     migrations.AddField(
    #         model_name='rating',
    #         name='author',
    #         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_rating', to=settings.AUTH_USER_MODEL),
    #     ),
    #     migrations.AddField(
    #         model_name='rating',
    #         name='post',
    #         field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_rating', to='posts.post'),
    #         preserve_default=False,
    #     ),
    # ]
