# Generated by Django 4.1.7 on 2023-12-05 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_alter_rating_education_alter_rating_management_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='salary',
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
