# Generated by Django 4.1.7 on 2023-12-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_rating_salary_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='article',
        ),
    ]
