# Generated by Django 4.1.7 on 2023-12-05 06:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_rating_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='article',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='article_rating', to='posts.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='salary',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
