# Generated by Django 4.1.7 on 2023-12-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rating_article_rating_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='work_time_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
