# Generated by Django 4.1.7 on 2023-12-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_work_time_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='company',
            field=models.CharField(default=1, max_length=1000, verbose_name='Работодатель'),
            preserve_default=False,
        ),
    ]
