# Generated by Django 4.1.7 on 2023-12-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='article',
        ),
        migrations.AddField(
            model_name='rating',
            name='post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_rating', to='posts.post'),
            preserve_default=False,
        ),
    ]
